version: '3.8'
name: local
volumes:
  postgres-data:
services:
  postgres:
    build: .
    container_name: ${DOCKER_CONTAINER_NAME}
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./config/postgresql.conf:/etc/postgresql.conf
    ports:
      - '${POSTGRES_PORT}:5432'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: postgres -c config_file=/etc/postgresql.conf
